export const data = [
    "Les filles prennent {drink}.",
    "Les garçons prennent {drink}.",
    "Le joueur le plus jeune distribue {drink}.",
    "{p1} siffle une chanson. Le premier qui devine distribue {drink}.",
    "La personne avec le plus de batterie prend {drink} (pour fêter ça).",
    "{drink} pour chaques personnes n'ayant pas le numéro de {p1}.",
    "{p1} imite le cri d'un animal. Si personne ne devine, tu prends {drink}.",
    "Prends {drink} si tu as plus de 80% de batterie.",
    "Prends {drink} si tu as moins de 20% de batterie.",
    "Fais un compliment à la personne à ta gauche ou prends {drink}.",
    "Les geeks boutonneux aux cheveux gras qui travaillent ou étudient dans l'informatique prennent {drink}.",
    "La prochaine personne qui sourist prend {drink}.",
    "Prend {drink} si tu préfère les chiens aux chats.",
    "{p1}, prend {drink} si tu souris dans les 10 prochaines secondes.",
    "Prennez une pénalité par allé au toilettes depuis le début de la soirée.",
    "{p1} choisis quelqu'un pour prendre {drink} avec toi.",
    "{p1} 1 pénalité par lettre dans ton prénom.",
    "{p1} va prendre un verre d'eau, ça te fera du bien.",
    "Tout ceux qui ont eu le covid prennent {drink}. Si personne ne l'a eu, {p1} prend {drink} pour tout le monde.",
    "Ceux qui viennent du sud prennent {drink}.",
    "{p1}, fait le grand écart ou prends {drink}.",
    "Le premier à sortir une capote distribue {drink}.",
    "{p1}, cite quelque chose que tu aimes, tous ceux qui n'aiment pas ça prennent {drink}. Si tout le monde aime, tu prends {drink}.",
    "Distribue {drink} si tu t'es fait quitter plus de 3 fois.",
    "{drink} si tu as déjà conduit bourré. Et {drink} en bonus parce que c'est vraiment pas bien.",
    "Prends {drink} si tu as déjà doublé par la droite.",
    "Le dernier à avoir pris l'avion entre {p1} et {p2} distribue {drink}.",
    "{p1} prochaine personne que tu regardes dans les yeux prend {drink}.",
    "Faite un tour de table des séries que vous regardez en ce moment. {drink} pour ceux qui regardent la même. #besties",
    "{drink} si tu es hétérosexuel(le). #orientationalert",
    "Le premier joueur à lecher le bout de son coude distribue 1 pénalité ultime. Ceux qui tente et échoue prennent {drink}.",
    "{p1} tu as l'occasion d'être un roi. Tu peux prendre une pénalité ultime et tout le monde t'appelle 'Sa Majesté' jusqu'a la fin de la partie, ou en distribuer {drink}.",
    "Tout ceux qui se sont masturbés aujourd'hui prennent {drink}. Vous êtes des animaux.",
    "{p1}, distribue autant de pénalité que de verres vidés par tout le monde depuis le début de la soirée.",
    "Les blonds distribuent {drink}.",
    "{p1}, récite les prénoms et âges de tous les joueurs présents. Pour chaque erreur, prends {drink}.",
    "{p1}, quelle est la date d'anniversaire de {p2} ? Si tu te trompes prends {drink}.",
    "{p1}, distribue {drink} à un joueur plus grand que toi en taille. S'il n'y en a pas, prends-les.",
    "{p1}, autant de pénalités que ton bodycount.",
    "Si t'as déjà regardé ton âge au fond d'un verre, prends {drink}.",
    "{p1}, prends autant de pénalités que tu veux. {p2} en prendras le double.",
    "{p1}, si tu trouves 2 arguments qui prouvent que {p2} mérite d'aller au paradis, distribue {drink}. Sinon prends-les.",
    "{p1}, donne le titre du dernier film que tu as vu. Ceux qui ne l'ont pas vu prennent {drink}.",

   
    {
        text: "{drink} si tu as déjà pleuré à cause {opt}.",
        options: [
            "d'un film d'amour",
            "d'une musique triste",
            "d'une rupture",
            "d'un oignon",
            "d'une dispute",
            "du roi lion",
            "d'un film de boule. Ok Kaaris",
        ]
    },
    {
        text: "{p1}, cite 3 marques de {opt} ou prends {drink}.",
        options: [
            "préservatifs",
            "voitures allemandes",
            "pâtes",
            "papiers toilette",
            "céréales",
            "vodka",
            "moto",
            "smartphone",
            "chaussures",
            "chocolat",
            "lessive",
            "vêtements de sport",
            "voitures électriques",
            "bières",
            "cigarettes",
            "sodas",
            "fast-food",
            "chips",
            "biscuits",
            "eau minérale",
            "café",
            "boissons énergisantes",
            "supermarchés",
            "maquillage",
            "luxe",
            "montres",
            "sacs à main",
            "sous-vêtements",
            "jeans",
            "parfums",
            "déodorants",
            "shampoings",
            "baskets",
            "plateformes de streaming",
            "consoles de jeux",
            "applis de rencontre",
            "opérateurs téléphoniques",
            "sites de voyage",
            "réseaux sociaux",
            "antivirus",
            "dentifrice",
            "lessive",
            "pneus",
            "stations essence",
            "outils de bricolage",
            "fournitures scolaires",
            "aliments pour animaux",
            "meubles",
            "appareils électroménagers",
            "whisky",
            "rhum",
            "sites pour adultes", // Si le jeu est +18
            "jeux de société",
            "marques de tabac à rouler"
        ]
    },
    {
        text: "{p1} et {p2} vous devez tout les deux {opt} si l'un de vous refuse, vous prenez {drink}.",
        options: [
            "faire 10 pompes",
            "confier votre fantasme",
            "citer un défaut chez {p3}",
            "ajouter de l'alcool dans votre verre",
            "échanger vos chaussures",
            "parler avec un accent jusqu'à la prochain carte qui évoque un de vous deux",
            "chanter le refrain de 'Libérée, Délivrée' en duo",
            "montrer la dernière photo de votre galerie",
            "faire la planche au sol pendant 30 secondes",
            "jouir très fort (pour de faux cochon)",
            "tourner 10 fois sur vous-même avant de vous rassoir",
            "changer de place avec les personne qui ont les places les moins confortable",
        ]
    },
    {
        text: "{p1} choisis entre {opt} ou une pénalité pour tout le monde.",
        options: [
            "donner {drink} à la dernière personne qui est arrivé(e)",
            "donner à voix haute le numéro de ta mère",
            "donner à voix haute le numéro de ton père",
            "sentir la chaussure de {p2}",
            "lire à voix haute ton dernier SMS reçu",
            "faire 20 pompes immédiatement",
            "montrer ton historique de recherche Google quand tu tapes 'porn'",
            "donner ton téléphone déverrouillé à {p2} pendant 1 minute",
            "Laisser {p2} te faire un mélange pour ton prochain verre",
            "masser les pieds de {p2} (avec ou sans chaussettes, au choix de {p2})",
            "imiter un orgasme très bruyant pendant 10 secondes",
            "lécher le coude de {p2}",
            "faire le tour de la pièce à quatre pattes en aboyant",
            "laisser {p2} choisir ta photo de profil sur un réseau social pour 24h",
            "te dessiner un monosourcil au stylo",
            "avoir un glaçon dans le dos (sous le t-shirt)",
            "manger une cuillère de moutarde",
            "boire l'équivalent d'un shot d'eau des toilettes",
            "mettre en note insta du patrick sébastien",
        ]
    },
    {
        text: "{p1} si tu trouves un argument solide {opt}, distribue {drink}. Sinon prends-les. Les autres, procédez à un vote pour déterminer si il a raison.",
        options: [
            "pour l'esclavage moderne",
            "pour le réchauffement climatique",
            "pour les pubs avant les vidéos YouTube",
            "pour les spoilers de séries",
            "contre des étrangers",
            "pour les dictatures",
            "contre la SPA",
            "pour élire Trump",
            "contre le féminisme",
            "contre les droits LGBT+",
            "pour TPMP",
            "contre le fait que {p2} soit un enculé",
            "pour le fait que {p2} soit une merde",
            "contre les associations caritatives",
            "contre le recyclage",
            "contre les vaccins",
            "pour les régimes extrêmes",
            "contre les droits des femmes",
            "pour la guerre",
            "contre la liberté d'expression",
            "pour la légalisation du braconnage",
            "contre la protection des animaux",
            "pour la pollution des océans",
        ]
    },
    {
        text: "Citez autant de {opt} que possible. {p1} prendra une pénalité pour chaque. Le jeu s'arrête à la moindre erreur.",
        options: [
            "capitales asiatiques",
            "nains de Blanche-Neige", 
            "planètes du système solaire", 
            "membres de la famille Kardashian",
            "pays limitrophes de la France", 
            "couleurs de l'arc-en-ciel",
            "films de la saga Harry Potter", 
            "rennes du Père Noël", 
            "membres des Beatles", 
            "océans du monde", 
            "choses que l'on trouve dans une trousse d'école",
            "ingrédients de la recette des crêpes",
            "tortues Ninja", 
            "présidents français",
            "titres de chansons de Céline Dion",
            "synonymes du mot 'ivre'",
            "les péchés capitaux",
            "les continents", // 5, 6 ou 7 selon la définition
            "les doigts de la main", 
            "les pièces du jeu d'échecs (types de pièces)",
            "les Merveilles du monde antique", // 7
            "les pierres d'infinité (Marvel)", // 6
            "les maisons de Poudlard", // 4
            "les sens", // 5
            "les animaux du zodiaque chinois", // 12 (Risqué pour P1 !)
            "les mousquetaires", // 4 (Athos, Porthos, Aramis, D'Artagnan)
            "dieux de l'olympe", // 12 principaux
            "d'acteurs pornos masculins",
            "d'actrices pornos féminines",
        
        ]
    },
];