export const data = [
  "Je n'ai jamais embrassé plus de 3 personnes en une soirée.",
  "Je n'ai jamais envoyé de nude par erreur.",
  "Je n'ai jamais vomi dans un Uber/Taxi.",
  "Je n'ai jamais fouillé dans le téléphone de mon partenaire.",
  "Je n'ai jamais menti sur mon âge.",
  "Je n'ai jamais eu de menottes aux poignets (police ou... autre).",
  "Je n'ai jamais fait semblant d'avoir un orgasme.",
  "Je n'ai jamais uriné dans une piscine publique.",
  "Je n'ai jamais oublié le prénom de la personne avec qui je couchais.",
  "Je n'ai jamais envoyé un message bourré que j'ai regretté.",
  "Je n'ai jamais fait semblant de ne pas voir un message.",
  "Je n'ai jamais dit 'j'arrive' alors que j'étais encore chez moi.",
  "Je n'ai jamais couché avec quelqu'un rencontré le même jour.",
  "Je n'ai jamais fait genre 'je m'en fous' alors que pas du tout.",

  "Je n'ai jamais cru qu'on me draguait alors que pas du tout.",
  "Je n'ai jamais dragué quelqu'un juste pour l'ego.",
  "Je n'ai jamais ignoré un message exprès.",
  "Je n'ai jamais répondu 'mdr' sans rire.",
  "Je n'ai jamais ghosté quelqu'un.",

  "Je n'ai jamais fini plus ivre que prévu.",
  "Je n'ai jamais oublié une partie de la soirée.",
  "Je n'ai jamais mélangé toutes les boissons.",
  "Je n'ai jamais proposé un after foireux.",

  "Je n'ai jamais cherché un truc qui était dans ma main.",
  "Je n'ai jamais oublié un anniversaire important.",
  "Je n'ai jamais confondu deux personnes.",
  "Je n'ai jamais couché avec plus de 3 personnes en même temps.",
  "Je n’ai jamais fait un 69 et regretté à cause de l’odeur.",
  "Je n’ai jamais été payé·e (ou ai payé) pour du sexe.",
  "Je n’ai jamais joui en moins de 30 secondes et fait genre c’était voulu",
  "Je n’ai jamais eu un rapport anal.",
  "Je n’ai jamais utilisé de jouet sexuel.",
  "Je n'ai jamais vomi sur quelqu'un.",
  "Je n'ai jamais eu de relation avec quelqu'un beaucoup plus âgé.",
  "Je n'ai jamais eu de relation avec quelqu'un beaucoup plus jeune.",
  "Je n’ai jamais pété bruyamment pendant un cunnilingus.",
  "Je n'ai jamais vomi dans un bar.",
  "Je n'ai jamais fait de strip-tease.",
  "Je n'ai jamais dormi dans le bus et raté mon arrêt.",
  "Je n'ai jamais fait semblant de connaître quelqu'un pour éviter une gêne.",
  "Je n'ai jamais porté les mêmes sous-vêtements trois jours de suite.",
];