export const data = [
  "Je n'ai jamais embrassé plus de 3 personnes en une soirée.",
  "Je n'ai jamais envoyé de nude par erreur.",
  "Je n'ai jamais vomi dans un Uber/Taxi.",
  "Je n'ai jamais fouillé dans le téléphone de mon partenaire.",
  "Je n'ai jamais menti sur mon âge.",
  "Je n'ai jamais eu de menottes aux poignets (police ou... autre).",
  "Je n'ai jamais fait semblant d'avoir un orgasme.",
  "Je n'ai jamais uriné dans une piscine publique.",
  "Je n'ai jamais dragué le/la partenaire d'un(e) ami(e).",
  "Je n'ai jamais oublié le prénom de la personne avec qui je couchais.",

  "Je n'ai jamais stalké un ex à 3h du matin.",
  "Je n'ai jamais envoyé un message bourré que j'ai regretté.",
  "Je n'ai jamais supprimé un message juste après l'avoir envoyé.",
  "Je n'ai jamais fait semblant de ne pas voir un message.",
  "Je n'ai jamais dit 'j'arrive' alors que j'étais encore chez moi.",
  "Je n'ai jamais embrassé quelqu'un que je ne connaissais pas.",
  "Je n'ai jamais regretté un bisou.",
  "Je n'ai jamais couché avec quelqu'un rencontré le même jour.",
  "Je n'ai jamais menti sur mes intentions.",
  "Je n'ai jamais fait genre 'je m'en fous' alors que pas du tout.",

  "Je n'ai jamais eu un crush gênant.",
  "Je n'ai jamais cru qu'on me draguait alors que pas du tout.",
  "Je n'ai jamais dragué quelqu'un juste pour l'ego.",
  "Je n'ai jamais ignoré un message exprès.",
  "Je n'ai jamais répondu 'mdr' sans rire.",
  "Je n'ai jamais trop analysé un message.",
  "Je n'ai jamais attendu une réponse avec impatience.",
  "Je n'ai jamais imaginé un scénario dans ma tête.",
  "Je n'ai jamais parlé d'une personne toute la soirée.",
  "Je n'ai jamais fait une crise de jalousie pour rien.",

  "Je n'ai jamais dit 'une dernière' et continué.",
  "Je n'ai jamais fini plus ivre que prévu.",
  "Je n'ai jamais oublié une partie de la soirée.",
  "Je n'ai jamais mélangé toutes les boissons.",
  "Je n'ai jamais dansé sans aucune gêne.",
  "Je n'ai jamais chanté faux avec confiance.",
  "Je n'ai jamais promis d'être raisonnable.",
  "Je n'ai jamais juré que j'allais me calmer.",
  "Je n'ai jamais renversé mon verre.",
  "Je n'ai jamais proposé un after foireux.",

  "Je n'ai jamais fait semblant de comprendre.",
  "Je n'ai jamais parlé tout seul.",
  "Je n'ai jamais cherché un truc qui était dans ma main.",
  "Je n'ai jamais ouvert le frigo sans raison.",
  "Je n'ai jamais oublié pourquoi j'étais entré dans une pièce.",
  "Je n'ai jamais procrastiné pour un truc simple.",
  "Je n'ai jamais fait les choses à la dernière minute.",
  "Je n'ai jamais été en retard sans bonne raison.",
  "Je n'ai jamais oublié un anniversaire important.",
  "Je n'ai jamais confondu deux personnes.",

  "Je n'ai jamais accepté un défi débile.",
  "Je n'ai jamais perdu un pari stupide.",
  "Je n'ai jamais prêté un truc et ne l'ai jamais revu.",
  "Je n'ai jamais exagéré une histoire.",
  "Je n'ai jamais coupé la parole.",
  "Je n'ai jamais vanné quelqu'un par amour.",
  "Je n'ai jamais proposé un plan nul.",
  "Je n'ai jamais voulu disparaître d'une soirée.",
  "Je n'ai jamais regretté d'être venu.",
  "Je n'ai jamais voulu rentrer trop tôt.",
  "Je n'ai jamais couché avec plus de 3 personnes en même temps.",
];