export const data = [
  "Qui pourrait finir en prison après une soirée trop arrosée ?",
  "Qui pourrait se marier avec un inconnu sur un coup de tête ?",
  "Qui pourrait survivre le plus longtemps sur une île déserte ?",
  "Qui pourrait devenir millionnaire par pur hasard ?",
  "Qui pourrait oublier le prénom de son partenaire pendant l'acte ?",
  "Qui pourrait pleurer devant une pub pour croquettes ?",
  "Qui pourrait tout plaquer pour élever des chèvres ?",
  "Qui pourrait coucher avec son ex ce soir ?",
  "Qui pourrait mourir le premier dans un film d'horreur ?",
  "Qui pourrait avoir une double vie secrète sans que personne ne le sache ?",

  "Qui pourrait envoyer un message et le regretter immédiatement ?",
  "Qui pourrait tomber amoureux en 5 minutes ?",
  "Qui pourrait partir en vacances sans rien organiser ?",
  "Qui pourrait se perdre dans son propre quartier ?",
  "Qui pourrait oublier pourquoi il est entré dans une pièce ?",
  "Qui pourrait mettre 12 alarmes et quand même se rendormir ?",
  "Qui pourrait commander un truc bizarre juste pour goûter ?",
  "Qui pourrait rire dans un moment totalement inapproprié ?",
  "Qui pourrait raconter une blague et la rater complètement ?",
  "Qui pourrait renverser son verre à chaque soirée ?",

  "Qui pourrait faire semblant de comprendre pour éviter de poser une question ?",
  "Qui pourrait stalker quelqu'un pendant 30 minutes puis ne rien faire ?",
  "Qui pourrait tomber dans les escaliers sans raison ?",
  "Qui pourrait oublier son code alors qu'il l'utilise tous les jours ?",
  "Qui pourrait dire 'j'arrive' alors qu'il est encore chez lui ?",
  "Qui pourrait manger un truc périmé en mode 'ça passe' ?",
  "Qui pourrait perdre ses clés alors qu'elles sont dans sa main ?",
  "Qui pourrait s'embrouiller avec un GPS ?",
  "Qui pourrait prendre la pire décision possible en soirée ?",
  "Qui pourrait croire à une fake news évidente ?",

  "Qui pourrait envoyer un vocal de 3 minutes pour dire 'ok' ?",
  "Qui pourrait oublier de répondre pendant 3 jours ?",
  "Qui pourrait se vexer pour rien ?",
  "Qui pourrait bouder puis oublier pourquoi ?",
  "Qui pourrait trop parler quand il est stressé ?",
  "Qui pourrait dire un secret sans faire exprès ?",
  "Qui pourrait rire à sa propre blague avant de la finir ?",
  "Qui pourrait mentir mal et se faire griller direct ?",
  "Qui pourrait faire un compliment hyper maladroit ?",
  "Qui pourrait se faire friendzoner en 2 phrases ?",

  "Qui pourrait tomber amoureux de la mauvaise personne ?",
  "Qui pourrait retourner avec son ex par faiblesse ?",
  "Qui pourrait draguer sans s'en rendre compte ?",
  "Qui pourrait croire que quelqu'un le drague alors que pas du tout ?",
  "Qui pourrait se faire un film pour rien ?",
  "Qui pourrait s'attacher trop vite ?",
  "Qui pourrait ghoster sans le vouloir ?",
  "Qui pourrait envoyer un message bourré et paniquer le lendemain ?",
  "Qui pourrait supprimer un message juste après l'avoir envoyé ?",
  "Qui pourrait écrire 'mdr' sans rire du tout ?",

  "Qui pourrait parler à un mur s'il y avait personne ?",
  "Qui pourrait se faire un monologue sous la douche ?",
  "Qui pourrait répéter une vanne jusqu'à ce qu'elle soit nulle ?",
  "Qui pourrait manger alors qu'il n'a pas faim ?",
  "Qui pourrait ouvrir le frigo 10 fois sans raison ?",
  "Qui pourrait dire 'dernière soirée' chaque week-end ?",
  "Qui pourrait dire 'je bois pas beaucoup' et finir éclaté ?",
  "Qui pourrait mélanger toutes les boissons ?",
  "Qui pourrait danser sans aucune gêne ?",
  "Qui pourrait chanter faux avec confiance ?",

  "Qui pourrait se lever pour aller quelque part et oublier pourquoi ?",
  "Qui pourrait chercher son téléphone avec la lampe de son téléphone ?",
  "Qui pourrait répondre 'quoi ?' alors qu'il a entendu ?",
  "Qui pourrait paniquer pour un truc inutile ?",
  "Qui pourrait procrastiner même pour des trucs simples ?",
  "Qui pourrait faire les choses au dernier moment ?",
  "Qui pourrait oublier un anniversaire important ?",
  "Qui pourrait se tromper de jour de la semaine ?",
  "Qui pourrait confondre deux personnes sans s'en rendre compte ?",
  "Qui pourrait saluer quelqu'un qui ne le saluait pas ?",

  "Qui pourrait croire qu'il est discret alors que pas du tout ?",
  "Qui pourrait tomber sur la mauvaise personne au mauvais moment ?",
  "Qui pourrait rater une opportunité évidente ?",
  "Qui pourrait se faire arnaquer par gentillesse ?",
  "Qui pourrait prêter un truc et ne jamais le revoir ?",
  "Qui pourrait perdre un pari stupide ?",
  "Qui pourrait accepter un défi débile ?",
  "Qui pourrait dire oui et regretter direct ?",
  "Qui pourrait se convaincre que c'était une bonne idée ?",
  "Qui pourrait dire 'ça va' alors que pas du tout ?",

  "Qui pourrait tout quitter pour changer de vie du jour au lendemain ?",
  "Qui pourrait vivre une situation de film sans s'en rendre compte ?",
  "Qui pourrait finir dans une histoire improbable ?",
  "Qui pourrait attirer les problèmes sans le vouloir ?",
  "Qui pourrait toujours être au mauvais endroit au mauvais moment ?",
  "Qui pourrait avoir une chance insolente ?",
  "Qui pourrait se sortir d'une galère par miracle ?",
  "Qui pourrait survivre à une apocalypse par accident ?",
  "Qui pourrait devenir célèbre sans comprendre pourquoi ?",
  "Qui pourrait disparaître d'une soirée sans prévenir ?",
  "Qui pourrait sucer un pote pour 'dépanner' ?",
  "Qui pourrait pousser sur une porte qui dit 'tirer' ?",
  "Qui est le plus susceptible de faire un blackout et de se réveiller chez un inconnu ?",
  "Qui est le plus susceptible de faire un strip-tease sur du Disney ?",
]