/* modes/rituel/cards/jeux/themes_data.js */
const themesData = [
    "des marques de bières",
    "des personnages de Disney",
    "des capitales européennes",
    "des positions sexuelles",
    "des types de drogues (médicinales ou non...)",
    "des marques de voitures",
    "des Pokémon de la 1ère génération",
    "des clubs de foot de Ligue 1",
    "des acteurs porno célèbres",
    "des noms de cocktails",
    "des applications de rencontre",
    "des excuses pour ne pas aller en cours/au taf",
    "des insultes",
    "des jeux de société",
    "des rappeurs français",
    "des parties du corps humain",
    "des marques de luxe",
    "des séries Netflix",
    "des marques de cigarettes",
    "des personnages de Harry Potter",
    "des marques de préservatifs",
    "des pays d'Afrique",
    "des ingrédients sur une pizza",
    "des super-héros Marvel",
    "des marques de téléphones portables",
    "des objets qu'on trouve dans une salle de bain",
    "des films Disney Pixar",
    "des types de fromages français",
    "des marques de baskets",
    "des chansons de Jean-Jacques Goldman",
    "des sites pornos",
    "des animaux de la ferme",
    "des chaînes de fast-food",
    "des États américains",
    "des personnages des Simpson",
    "des marques de maquillage",
    "des sports olympiques",
    "des youtubeurs français connus",
    "des marques de céréales",
    "des méchants de cinéma",
    "des synonymes du mot 'sexe' ou 'baiser'",
    "des marques de sous-vêtements",
    "des émissions de télé-réalité",
    "des fruits rouges",
    "des instruments de musique",
    "des desserts",
    "un plat de spécialité asiatique",
    "des marques de chocolat",
    "des présidents / rois français",
    "des personnages de Game of Thrones",
    "des choses qu'on peut fumer",
    "des réseaux sociaux",
    "des marques de voitures allemandes",
    "des races de chiens",
    "des signes astrologiques",
    "des endroits insolites pour faire l'amour",
    "des marques de jeux vidéo (éditeurs ou consoles)",
    "des prénoms composés",
    "des animaux marins",
    "des marques d'eau minérale",
    "des films d'horreur cultes",
    "des outils de bricolage",
    "des cris d'animaux (le nom du cri)",
    "des joueurs de l'équipe de France de football (toutes époques)",
    "des objets ronds",
    "des personnages de Mario",
    "des marques de montres",
    "des titres de films avec un chiffre dedans",
    "des capitales",
    "des coktails",
    "des surnoms qu'on donne à un penis",
    "quelque chose qu'on peut dire en repas de famille et pendant le coït",

];

export default themesData;