/* modes/rituel/cards/jeux/tu_preferes_data.js */

export default [
    { a: "Boire tout ce que tu bois à la paille", b: "Manger tout ce que tu manges avec des baguettes" },
    { a: "Ne plus jamais boire d'alcool", b: "Ne plus jamais manger de fromage" },
    { a: "Toujours sentir l'oignon", b: "Toujours sentir le poisson" },
    { a: "Vivre sans musique", b: "Vivre sans film ni série" },
    { a: "Savoir quand tu vas mourir", b: "Savoir comment tu vas mourir" },
    { a: "Être invisible", b: "Pouvoir voler" },
    { a: "Devoir dire tout ce que tu penses", b: "Ne plus jamais pouvoir parler" },
    { a: "Boire 10 gorgées maintenant", b: "Distribuer 10 gorgées mais faire la vaisselle demain" },
    { a: "Avoir des bras de T-Rex (très courts)", b: "Avoir des jambes de 10 cm" },
    { a: "Péter bruyamment à chaque fois que tu embrasses quelqu'un", b: "Roter à chaque fois que tu as un orgasme" },
    { a: "Que tes parents voient ton historique internet", b: "Que tes parents voient ta galerie photo" },
    { a: "Avoir des cheveux en spaghettis (cuits)", b: "Transpirer de la mayonnaise" },
    { a: "Porter des sous-vêtements mouillés à vie", b: "Avoir tout le temps un caillou dans ta chaussure" },
    { a: "Te battre contre un canard de la taille d'un cheval", b: "Te battre contre 100 chevaux de la taille d'un canard" },
    { a: "Être la personne la plus drôle de la pièce mais moche", b: "Être la personne la plus belle mais super ennuyeuse" },
    { a: "Ne pouvoir chuchoter que très fort", b: "Ne pouvoir que crier tout ce que tu dis" },
    { a: "Coucher avec la personne à ta droite", b: "Coucher avec la personne à ta gauche" },
    { a: "Avoir un nez rouge de clown permanent", b: "Avoir des dents de lapin géantes" },
    { a: "Vivre dans une maison hantée", b: "Vivre avec ton ex dans un studio" },
    { a: "Manger un caca au goût de chocolat", b: "Manger du chocolat au goût de caca" },
    { a: "Ne plus jamais avoir internet", b: "Ne plus jamais pouvoir voyager" },
    { a: "Surprendre tes parents en train de le faire", b: "Que tes parents te surprennent en train de le faire" },
    { a: "Avoir des mamelons à la place des yeux", b: "Avoir des yeux à la place des mamelons" },
    { a: "Devoir rire à chaque phrase triste", b: "Devoir pleurer à chaque blague drôle" },
    { a: "Avoir l'haleine de ton chien", b: "Avoir l'odeur corporelle de ton chat" },
    { a: "Faire pipi au lit à chaque fois que tu es bourré(e)", b: "Vomir sur tes chaussures à chaque soirée" },
    { a: "Être allergique à l'alcool", b: "Être allergique au sucre" },
    { a: "Avoir une tête immense sur un petit corps", b: "Avoir une petite tête sur un corps immense" },
    { a: "Que personne ne vienne à ton mariage", b: "Que personne ne vienne à ton enterrement" },
    { a: "Recommencer ta vie à zéro avec tes connaissances actuelles", b: "Recevoir 10 millions d'euros tout de suite" },
    { a: "Avoir le hoquet pour le restant de tes jours", b: "Avoir la sensation d'éternuer sans que ça sorte à vie" },
    { a: "Porter une couche culotte visible en soirée", b: "Porter une tétine à la bouche en soirée" },
    { a: "Avoir des mains à la place des pieds", b: "Avoir des pieds à la place des mains" },
    { a: "Devoir danser dès qu'il y a de la musique", b: "Devoir chanter dès que quelqu'un dit ton prénom" },
    { a: "Avoir des dents en cheveux", b: "Avoir des cheveux en dents" },
    { a: "Devoir toujours courir partout (jamais marcher)", b: "Devoir toujours marcher à reculons" },
    { a: "Être riche mais tout le monde te déteste", b: "Être pauvre mais tout le monde t'adore" },
    { a: "Avoir un bruit de klaxon à chaque fois que tu clignes des yeux", b: "Avoir un bruit de pet à chaque pas que tu fais" },
    { a: "Recevoir une notification à chaque fois que quelqu'un pense à toi sexuellement", b: "Recevoir une notification à chaque fois que quelqu'un dit du mal de toi" },
    { a: "Ne plus jamais avoir besoin de dormir", b: "Ne plus jamais avoir besoin de manger" },
    { a: "Avoir la tête de la taille d'une balle de tennis", b: "Avoir la tête de la taille d'une pastèque géante" },
    { a: "Devoir porter une robe de mariée à chaque enterrement", b: "Devoir porter un maillot de bain à chaque entretien d'embauche" },
    { a: "Manger une pizza à l'ananas à chaque repas", b: "Manger des céréales avec de l'eau à chaque petit-déjeuner" },
    { a: "Avoir des bras de 3 mètres de long", b: "Avoir un cou de girafe" },
    { a: "Que ta vie soit une comédie musicale (tu dois chanter)", b: "Que ta vie soit une sitcom (avec des rires enregistrés quand tu te rates)" },
    { a: "Échanger de corps avec ton père/ta mère pour 24h", b: "Échanger de corps avec ton chien pour une semaine" },
    { a: "Être obligé de dire 'Wesh' à la fin de chaque phrase", b: "Être obligé de faire une révérence à chaque fois que tu dis bonjour" },
    { a: "Avoir un orgasme à chaque fois que tu entends ton prénom", b: "Avoir envie de vomir à chaque fois que tu vois un bébé" },
    { a: "Pouvoir lire dans les pensées mais uniquement les pensées sales", b: "Pouvoir voir à travers les vêtements mais uniquement des personnes de plus de 80 ans" },
    { a: "Ne pouvoir utiliser que du papier toilette usagé", b: "Ne pouvoir utiliser que du papier de verre comme papier toilette" },
    { a: "Avoir des mains qui sentent le jambon en permanence", b: "Avoir des oreilles qui pendent jusqu'aux épaules" },
    { a: "Tuer 5 inconnus pour sauver ton animal de compagnie", b: "Tuer ton animal de compagnie pour sauver 5 inconnus" },
    { a: "Être attaqué par un aigle une fois par mois", b: "Être attaqué par une poule tous les jours" },
    { a: "Avoir une troisième jambe fonctionnelle", b: "Avoir une troisième main qui sort du ventre" },
    { a: "Devoir lécher la barre du métro", b: "Devoir boire un verre de l'eau des toilettes" },
    { a: "Qu'on te coupe un doigt (tu choisis lequel)", b: "Qu'on t'arrache toutes les dents (sans anesthésie)" },
    { a: "Passer un an seul sur une île déserte", b: "Passer un an en prison dans une cellule surpeuplée" },
    { a: "Toujours avoir du sable dans ton lit", b: "Toujours avoir une sensation de chaussette mouillée" },
    { a: "Boire 5 shots maintenant", b: "Envoyer un SMS risqué à la 3ème personne de tes contacts" },
];